/*consulta*/
/*Cuantos cuerpos han sido enterrados y cuales son lo de genero femenino?*/
SELECT
OBSERVACIONES AS OBSERVACION,
SEXO_FALLECIDO AS SEXO_FALLECIDO,
COUNT(SEXO_FALLECIDO)as CANTIDAD
FROM 
PUBLIC.DETALLEENTIERRO
INNER JOIN PUBLIC.FALLECIDO ON FALLECIDO.F_ID = DETALLEENTIERRO.F_ID
WHERE
(SEXO_FALLECIDO like '%F%') OR (SEXO_FALLECIDO like '%M%')
GROUP BY
OBSERVACIONES,SEXO_FALLECIDO
ORDER BY
OBSERVACIONES ASC;

/*Cuantos clientes cuentan con panteón ?*/
SELECT
DESCRIPCION_TUMBA AS DESCRIPCION_TUMBA,
DESCRIPCION_SECTOR AS TIPO_TUMBA,
COUNT(DESCRIPCION_SECTOR)as CLIENTE_CON_PANTEON
FROM
PUBLIC.TUMBA
INNER JOIN PUBLIC.SECTOR ON SECTOR.ID_SECTOR = TUMBA.ID_TUMBA
WHERE
SECTOR.DESCRIPCION_SECTOR = 'PANTEON'
GROUP BY
DESCRIPCION_TUMBA,DESCRIPCION_SECTOR;

/*Cuantos fallecidos son menores de edad ?*/
SELECT
SEXO_FALLECIDO AS SEXO_FALLECIDO,
COUNT(SEXO_FALLECIDO)as FALLECIDOS_MENORES_DE_EDAD
FROM 
PUBLIC.DETALLEENTIERRO
INNER JOIN PUBLIC.FALLECIDO ON FALLECIDO.F_ID = DETALLEENTIERRO.F_ID
WHERE
(SEXO_FALLECIDO like '%F%') OR (SEXO_FALLECIDO like '%M%') OR FALLECIDO.F_EDAD<18
GROUP BY
SEXO_FALLECIDO;

/*MANTENIMIENTOS REALIZADOS POR LOS EMPLEADOS*/
SELECT
EM_NOMBRE AS NOMBRE_EMPLEADO,
EM_APELLIDO AS APELLIADO_EMPLEADO,
OBSERVACION_DETALLEMANTE AS MANTENIMIENTO
FROM DETALLEMANTENIMIENTO
INNER JOIN EMPLEADO ON DETALLEMANTENIMIENTO.ID_MANTENIMIENTO = EMPLEADO.EM_ID